package com.resumethinking.platform.resumes;

import com.resumethinking.platform.auth.UserRole;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import java.time.Instant; import java.util.*;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.web.multipart.MultipartFile;
import com.resumethinking.platform.crypto.AesGcmCryptoService;

@RestController @RequestMapping("/api/v1")
public class ResumeController {
 private final ResumeLifecycleService service; private final AesGcmCryptoService crypto; public ResumeController(ResumeLifecycleService service){this(service,null);} public ResumeController(ResumeLifecycleService service,AesGcmCryptoService crypto){this.service=service;this.crypto=crypto;}
 @PostMapping(value="/resumes", consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<Response> upload(@RequestAttribute("actorId") UUID actor,@RequestAttribute("role") UserRole role,@RequestPart("file") MultipartFile file,@RequestParam(required=false) String title) throws java.io.IOException { String name=file.getOriginalFilename()==null?"resume.txt":file.getOriginalFilename(); String lower=name.toLowerCase(java.util.Locale.ROOT); Resume.SourceType type; if(lower.endsWith(".txt")) type=Resume.SourceType.TXT; else if(lower.endsWith(".docx")) type=Resume.SourceType.DOCX; else throw new IllegalArgumentException("UNSUPPORTED_FILE"); if(file.getSize()>5_000_000) throw new IllegalArgumentException("PAYLOAD_TOO_LARGE"); if(crypto==null) throw new IllegalStateException("encryption unavailable"); String safeTitle=(title==null||title.isBlank())?name.substring(0,Math.min(200,name.length())):title; if(safeTitle.length()>200) throw new IllegalArgumentException("VALIDATION_ERROR"); var encrypted=crypto.encryptBytes(file.getBytes()); return ResponseEntity.status(HttpStatus.CREATED).body(Response.from(service.upload(actor,role,safeTitle,type,encrypted.ciphertext(),encrypted.nonce()))); }
 @GetMapping("/resumes") public Page list(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){int p=normalizedPage(page),s=normalizedSize(pageSize); return Page.from(service.listActive(actorId,role,PageRequest.of(p-1,s,Sort.by("id"))),p,s);}
 @GetMapping("/resumes/{id}") public Response get(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@PathVariable UUID id){return Response.from(service.getActive(id,actorId,role));}
 @DeleteMapping("/resumes/{id}") public Response delete(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@PathVariable UUID id,@Valid @RequestBody DeleteRequest body){return Response.from(service.softDelete(new DeleteResumeCommand(id,actorId,role,body.confirmationText(),body.expectedVersion())));}
 @PostMapping("/recovery/resumes/{id}/restore") public Response restore(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@PathVariable UUID id,@Valid @RequestBody RestoreRequest body){if(role!=UserRole.USER) throw new org.springframework.security.access.AccessDeniedException("FORBIDDEN"); return Response.from(service.recover(id,actorId,role,body.expectedVersion()));}
 @PostMapping("/admin/recovery/resumes/{id}/restore") public Response adminRestore(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@PathVariable UUID id,@Valid @RequestBody RestoreRequest body){if(role!=UserRole.ADMIN) throw new org.springframework.security.access.AccessDeniedException("FORBIDDEN"); return Response.from(service.recover(id,actorId,role,body.expectedVersion()));}
 @DeleteMapping("/admin/recovery/resumes/{id}") public Response adminDelete(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@PathVariable UUID id,@Valid @RequestBody DeleteRequest body){if(role!=UserRole.ADMIN) throw new org.springframework.security.access.AccessDeniedException("FORBIDDEN"); return Response.from(service.softDelete(new DeleteResumeCommand(id,actorId,role,body.confirmationText(),body.expectedVersion())));}
 @GetMapping("/recovery/resumes") public Page recovery(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){if(role!=UserRole.USER) throw new org.springframework.security.access.AccessDeniedException("FORBIDDEN"); int p=normalizedPage(page),s=normalizedSize(pageSize); return Page.from(service.listRecoverable(actorId,role,null,PageRequest.of(p-1,s,Sort.by("id"))),p,s);}
 @GetMapping("/admin/recovery/resumes") public Page adminRecovery(@RequestAttribute("actorId") UUID actorId,@RequestAttribute("role") UserRole role,@RequestParam(required=false) UUID ownerId,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){if(role!=UserRole.ADMIN) throw new org.springframework.security.access.AccessDeniedException("FORBIDDEN"); int p=normalizedPage(page),s=normalizedSize(pageSize); return Page.from(service.listRecoverable(actorId,role,ownerId,PageRequest.of(p-1,s,Sort.by("id"))),p,s);}
 public record DeleteRequest(@NotBlank String confirmationText,@Min(0) long expectedVersion){} public record RestoreRequest(@Min(0) long expectedVersion){}
 private static int normalizedPage(int page){return Math.max(1,page);} private static int normalizedSize(int size){return Math.max(1,Math.min(100,size));}
 public record Page(List<Response> items,int page,int pageSize,long totalItems,int totalPages){static Page from(org.springframework.data.domain.Page<Resume> data,int page,int size){return new Page(data.getContent().stream().map(Response::from).toList(),page,size,data.getTotalElements(),data.getTotalPages());}}
 public record Response(UUID id,UUID ownerId,String title,Resume.SourceType sourceType,int status,VisibilityState visibilityState,long version,Instant visibleUntil,Instant softDeletedAt,Instant archivedAt,Instant restoredAt,Instant createdAt,Instant updatedAt){static Response from(Resume r){return new Response(r.getId(),r.getOwnerId(),r.getTitle(),r.getSourceType(),r.getStatus(),r.getVisibilityState(),r.getVersion(),r.getVisibleUntil(),r.getSoftDeletedAt(),r.getArchivedAt(),r.getRestoredAt(),r.getCreatedAt(),r.getUpdatedAt());} static Response from(ResumeView r){return new Response(r.id(),r.ownerId(),r.title(),r.sourceType(),r.status(),r.visibilityState(),r.version(),r.visibleUntil(),r.softDeletedAt(),r.archivedAt(),r.restoredAt(),r.createdAt(),r.updatedAt());}}
}
